[tool.poetry]
name = "girder-4"
version = "0.1.0"
description = "Documentation for Girder"
authors = ["Kitware D&A Team <data-analytics@kitware.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
sphinx-copybutton = "^0.5.0"
sphinx-notfound-page = "^0.8"
sphinx-panels = "^0.6.0"
furo = "^2022.4.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
