name: Build Documentation
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements_doc.txt
      - name: Build Documentation
        working-directory: doc
        run: make html
      - name: Stash build
        uses: actions/upload-artifact@v3
        with:
          name: doc-build
          path: doc/build

  deploy:
    name: Publish Documentation
    runs-on: ubuntu-latest
    needs: build-doc
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: doc-build
          path: doc/build
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
          # cname: docs.girder.com
